### Welcome Page
http://localhost:8080/

### Login User
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email": "Avyan123@gmail.com",
    "password": "password"
}

### Create User
POST http://localhost:8080/api/admin/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4MjE3NjQ3MH0.hSoKhOVcM54AwWechMDCBGMiuUQsHC0N_QelYB1PlFY

{
    "email": "Avyan@gmail.com",
    "name": "Avyan",
    "password":"password",
    "isAdmin": 0
}

### Update User
PUT http://localhost:8080/api/admin/users/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4MjE3NjQ3MH0.hSoKhOVcM54AwWechMDCBGMiuUQsHC0N_QelYB1PlFY

{
    "email": "Avyan123@gmail.com",
    "name": "Avyan123",
    "password":"password",
    "isAdmin": 0
}


### Create Group
POST  http://localhost:8080/api/groups
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODIxNzY1NDF9.hTCrbDYo493D8GeI1bYva3LFQ_P63lwLszdu7xIPSUU

{
  "name": "My Group1",
  "description": "This is a test group"
}

### Delete Group
DELETE http://localhost:8080/api/groups/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODIxNzY1NDF9.hTCrbDYo493D8GeI1bYva3LFQ_P63lwLszdu7xIPSUU

### Search Group
GET http://localhost:8080/api/groups?q=Group
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODIxNzY1NDF9.hTCrbDYo493D8GeI1bYva3LFQ_P63lwLszdu7xIPSUU

### Add Members to Group
POST http://localhost:8080/api/groups/1/members
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODIxNzY1NDF9.hTCrbDYo493D8GeI1bYva3LFQ_P63lwLszdu7xIPSUU

{
  "userIds": [1, 3]
}

### Send message in group.
POST http://localhost:8080/api/groups/1/messages
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODIxNzY1NDF9.hTCrbDYo493D8GeI1bYva3LFQ_P63lwLszdu7xIPSUU

{
  "content": "Hello worldfafashfsdhfahdsf"
}

### Like any particular message.
POST http://localhost:8080/api/messages/2/like
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4MjE3NjQ3MH0.hSoKhOVcM54AwWechMDCBGMiuUQsHC0N_QelYB1PlFY